### ISSUE TITLE
Deploying a custom dashboard at startup

### ISSUE THREAD

**Issue by clrosier** [newrelic/newrelic-unix-monitor#30]
Hi everyone.
I was wondering if it's possible to deploy a custom dashboard at plugin startup as opposed to the 7 default ones that get created.

Can dashboards be defined by a json file or something like that?

Thank you!

**Comment by sschwartzman** [comment]
Hi @clrosier - unfortunately that's not doable with what we have set up here. This dashboard deployment is a lambda we have running that pulls the dashboards from S3 depending on which service (in this case unix monitor) is asking. That said, I'd be happy to provide you the lambda code as a Gist to run yourselves, then you'd just have to change the start shell script to point at your lambda endpoint rather than ours.

If you want that src, let me know!

**Comment by clrosier** [comment]
That would be really cool if you could provide that for us! I'd really appreciate that personally :)

**Comment by sschwartzman** [comment]
@clrosier so I went back and looked and it's a little more complex than can be dropped into a single Gist. How urgent is this request? I ask because I need to figure out what makes sense in terms of releasing it or just guiding you through what it's doing.
