### ISSUE TITLE
Data Not Showing for machine running SunOS 

### ISSUE THREAD

**Issue by shabzshkh** [newrelic/newrelic-unix-monitor#6]
Hi Team,

None of the stats are showing up when we installed new relic plugin on SunOS. We are getting the below error. We tried installing the new plugin but the error is still the same:

Plugin location: /opt/unix-infra-monitor
Java location: /usr/bin/java
Java version: 1.6.0_21
grep: illegal option -- q
Usage: grep -hblcnsviw pattern file . . .
Running as plugin that posts directly to Insights.
./pluginctl.sh: syntax error at line 236: `admin_api_key=$' unexpected

**Comment by sschwartzman** [comment]
In line 1, try changing #!/bin/sh to #!/bin/bash or #!/bin/ksh. Let me know if that works.

**Comment by sschwartzman** [comment]
Any update here @shabzshkh ?

**Comment by shabzshkh** [comment]
Seth,

The plugin is running fine but the data is not reporting. This is the o/p it throws, when I changed to #!/bin/bash and #!/bin/ksh

# ./pluginctl.sh start
Plugin location: /opt/unix-infra-monitor
Java location: /usr/bin/java
Java version: 1.6.0_21
grep: illegal option -- q
Usage: grep -hblcnsviw pattern file . . .
Running as plugin that posts directly to Insights.

Checking New Relic Unix Plugin
New Relic Unix Plugin is running with PID 18937

Regards,
Shahbaz

**Comment by shabzshkh** [comment]
Hi Seth,

Any update here.

Regards,
Shahbaz

**Comment by shabzshkh** [comment]
Hi Seth,

Following up to see if you have any update on this issue.

Regards,
Shahbaz

**Comment by sschwartzman** [comment]
I have to see the output beyond what the script is saying at command line. Do you have any logs to share?

**Comment by sschwartzman** [comment]
@shabzshkh I took a look in pluginctl.sh and I don't see `grep -q` anywhere. Is your copy of pluginctl.sh modified in any other way than changing the hashbang line?

**Comment by shabzshkh** [comment]
@sschwartzman We do see **grep -c -q** in pluginctl.sh. See snippet attached. 

![image](https://user-images.githubusercontent.com/43442563/48912503-cf4be800-ee9b-11e8-99d9-a5196b84492b.png)

**Comment by sschwartzman** [comment]
That was fixed in the version released in July, so it sounds like you just need to upgrade. Have you tried the latest release?

This is what it looks like now: https://github.com/newrelic/newrelic-unix-monitor/blob/master/pluginctl.sh#L96

**Comment by shabzshkh** [comment]
Hi Seth,


Thank you for your email.


Yes we have used the latest version. Is it possible for you to provide the zip file of the updated plugin?


Regards,
Shahbaz Shaikh
Tech Ops Specialist
Technical Operations Center | Yesmail Interactive
866.275.7678 | TOC@yesmail.com
www.yesmail.com<http://www.yesmail.com>


________________________________

**Comment by sschwartzman** [comment]
I just checked the latest release (from Sept 7th). It does have the corrected `pluginctl.sh` in it. So it would seem that you are not using the right release.

Please get it here: https://github.com/newrelic/newrelic-unix-monitor/releases/latest

**Comment by shabzshkh** [comment]
Thank you, Seth. Let me give it try.

Regards,
Shahbaz

**Comment by shabzshkh** [comment]
Hi Seth,

We did try installing the latest new relic plugin but unfortunately, the data isn’t showing up in New Relic. Can you please advise on what could be causing this issue?

Regards,
Shahbaz

From: Shaikh, Shahbaz
Sent: Wednesday, December 05, 2018 12:43 PM
To: newrelic/newrelic-unix-monitor
Subject: RE: [newrelic/newrelic-unix-monitor] Data Not Showing for machine running SunOS (#6)

Thank you, Seth. Let me give it try.

Regards,
Shahbaz

**Comment by shabzshkh** [comment]
Hi Seth,

We tried installing the latest plugin but the data is still not showing up in New Relic UI under Plugins.

Regards,
Shahbaz

**Comment by sschwartzman** [comment]
It doesn't report under Plugins, it shows up in Insights. Please check there.

**Comment by polarahul** [comment]
Hi Seth ,
Executed this query in Insight and did not show up any results for cosyesorap01 host
**Query::**
SELECT latest(timestamp) as 'Last Reported', 100-latest(`cpu.idle`) as 'CPU Use %', 100*latest(`memory.used`)/(latest(`memory.used`)+latest(`memory.free`)) as 'Memory Use %', max(percentUsed) as 'Fullest Disk %' from `unixMonitor:Disk`, `unixMonitor:Stats` since 1 hour ago WHERE hostname='cosyesorap01'

![image](https://user-images.githubusercontent.com/45857507/49959463-767fd600-fec2-11e8-8202-19eb5bcf4d93.png)

Also tried this (Unix Disk) from Data Explorer  for 1 month period and cosyesorap01 is listed and last reporting was on 12/05
https://insights.newrelic.com/accounts/989437/explorer/events?eventType=unixMonitor:Disk&duration=2592000000&facet=hostname

![image](https://user-images.githubusercontent.com/45857507/49959785-6ae0df00-fec3-11e8-95b2-c4b396753ac0.png)


-Rahul

**Comment by sschwartzman** [comment]
Looks like it's reporting just fine to me. For your first query, I had to change the parameters because it's Solaris, so the memory figures it reports aren't necessarily the same as Linux, but can be acted on with simple math to get the same result: https://insights.newrelic.com/accounts/989437/query?query=SELECT%20latest(timestamp)%20as%20%27Last%20Reported%27,%20100-latest(%60cpu.idle%60)%20as%20%27CPU%20Use%20%25%27,%20100-(100*latest(%60memory.free%60)%2Flatest(%60memory.total%60))%20as%20%27Memory%20Use%20%25%27,%20max(percentUsed)%20as%20%27Fullest%20Disk%20%25%27%20from%20%60unixMonitor:Disk%60,%20%60unixMonitor:Stats%60%20since%201%20hour%20ago%20WHERE%20hostname%3D%27cosyesorap01%27

For the total number of events coming from cosyesorap01, I just shortened the time frame: https://insights.newrelic.com/accounts/989437/query?query=SELECT%20count(*)%20FROM%20%60unixMonitor:Disk%60,%20%60unixMonitor:DiskIO%60,%20%60unixMonitor:NetworkIO%60,%20%60unixMonitor:Process%60,%20%60unixMonitor:Stats%60,%20%60unixMonitor:Vmstat%60%20SINCE%203%20hours%20AGO%20WHERE%20hostname%20%3D%20%27cosyesorap01%27%20facet%20eventType()%20TIMESERIES

Looks like it started reporting around Noon ET Today (Friday). I faceted by eventType to see that all of the expected event types are there (disk, process, etc).

So are we all set now?

**Comment by shabzshkh** [comment]
Thank you for all your help, Seth. I see the data now. Please feel free to close this issue.

Regards,
Shahbaz
